"""fresh new

Revision ID: ecbf743f2d8a
Revises: 
Create Date: 2025-07-01 13:35:06.162042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbf743f2d8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dates_id'), 'dates', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('sale_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_points_id'), 'sale_points', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_sale_point', sa.Integer(), nullable=False),
    sa.Column('id_date', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_date'], ['dates.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_sale_point'], ['sale_points.id'], ),
    sa.PrimaryKeyConstraint('id_product', 'id_sale_point', 'id_date')
    )
    op.create_table('product_sale_points',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_sale_point', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_sale_point'], ['sale_points.id'], ),
    sa.PrimaryKeyConstraint('id_product', 'id_sale_point')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_sale_points')
    op.drop_table('prices')
    op.drop_index(op.f('ix_sale_points_id'), table_name='sale_points')
    op.drop_table('sale_points')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_dates_id'), table_name='dates')
    op.drop_table('dates')
    # ### end Alembic commands ###
